on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scan Terraform 
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        iac_dir: 'test_dirs/fail/'
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:
    
  terrascan-k8s:
    runs-on: ubuntu-latest
    name: terrascan-action-k8s
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scan k8s 
      id: terrascan-k8s
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'k8s'
        #iac_version: 'v14'
        policy_type: 'k8s'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        iac_dir: 'test_dirs/k8s/vul-k0s-helm-docker/kubeyaml/'
        #policy_path:
        #skip_rules:
        #config_path:
  
  
  
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        skip: ./.git
  

