on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action-terraform
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scan Terraform 
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        iac_dir: 'test_dirs/fail/'
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:
        
    - name: Upload SARIF file 
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif    
  
  terrascan-k8s:
    runs-on: ubuntu-latest
    name: terrascan-action-k8s
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Scan Terraform 
      id: terrascan-k8s
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        #iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        #non_recursive:
        iac_dir: '/test_dirs/k8s/vul-k0s-helm-docker'
        #policy_path:
        #skip_rules:
        #config_path:
        #webhook_url:

          
    - name: Upload SARIF file 1
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
